[package]
name = "publicrypto"
version = "0.1.0"
authors = []

[addresses]
publicrypto = "_"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = 'main'
subdir = 'aptos-move/framework/aptos-stdlib'

